services:
  redpanda:
    image: redpandadata/redpanda:v24.1.1
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local-redpanda"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "redpanda:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "dummy"  # Redpanda doesn't need ZK, but UI requires a value
    depends_on:
      - redpanda
